name: flutter_pagination_app
description: "A new Flutter project."
publish_to: 'none'  # Keep this line if you don't want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  go_router: ^5.0.0 
  fpdart: ^1.1.1 
  http: ^1.2.2       
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.9.0  
  flutter_lints: ^5.0.0  

flutter:
  uses-material-design: true
